site_name: VP_KB_2
site_description: AI Chatbot Knowledge Center for multiple platforms
site_author: wikigoo
site_url: https://wikigoo.github.io/VP-KB-v1/

# Repository
repo_name: VP-KB-v1
repo_url: https://github.com/wikigoo/VP-KB-v1
edit_uri: edit/main/docs/

# Theme Configuration
theme:
  name: material
  custom_dir: overrides
  palette:
    # Dark theme as default
    scheme: slate
    primary: black
    accent: blue
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/logo.png
  favicon: assets/favicon.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
  
# Custom CSS
extra_css:
  - stylesheets/extra.css

# Custom JavaScript
extra_javascript:
  - javascripts/extra.js

# Social/Footer Links
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/yourhandle
      name: Twitter
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/yourhandle
      name: Instagram
    - icon: fontawesome/brands/telegram
      link: https://t.me/yourhandle
      name: Telegram
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@yourhandle
      name: YouTube
  
  # Custom sidebar links (before download buttons)
  custom_links:
    - name: Documentation
      url: /documentation/
      icon: "📚"
    - name: Tutorials
      url: /tutorials/
      icon: "🎓"
    - name: API Reference
      url: /api/
      icon: "⚙️"

# Copyright
copyright: Some rights reserved 2025©

# Navigation Structure
nav:
  - Home: index.md
  - Chatbot Implementations:
      - Overview: chatbots/index.md
      - Gemini-GEM: chatbots/gemini.md
      - ChatGPT-GPT: chatbots/chatgpt.md
      - Claude-Project: chatbots/claude.md
  - Categories:
      - AI Tools: categories/ai-tools.md
      - Digital Investigation: categories/digital-investigation.md
      - Journalism: categories/journalism.md
      - Podcast: categories/podcast.md
      - Video Production: categories/video-production.md
  - Creative Content:
      - Blog Post Writer: creative/blog-writer.md
      - Podcast Scripts: creative/podcast-scripts.md
      - News Writer: creative/news-writer.md
      - AI Content Tools: creative/ai-tools.md
  - Educational Consultants:
      - Nature Photography: education/nature-photography.md
      - Documentary Editing: education/documentary-editing.md
      - Deep Research: education/deep-research.md
      - Avid News Editor: education/avid-editor.md
      - AI Journalism: education/ai-journalism.md
  - Equipment Guides:
      - News Video Production: equipment/news-production.md
      - Adobe Premiere 2025: equipment/adobe-premiere.md
      - Canon R8 Camera: equipment/canon-r8.md
      - Sony Z90 Camera: equipment/sony-z90.md
      - vMix Streaming: equipment/vmix.md

# Plugins
plugins:
  - search:
      lang: en
      separator: '[\s\-\.]+'
  - tags
  - minify:
      minify_html: true

# Markdown Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
