site_name: VP-KB-v1
site_url: https://wikigoo.github.io/VP-KB-v1
repo_url: https://github.com/wikigoo/VP-KB-v1
repo_name: VP-KB-v1

theme:
  name: material
  language: en
  palette:
    scheme: slate
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - toc.integrate
    - content.code.annotate
    - content.tabs.link
    - content.action.edit

markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
  - tables
  - codehilite
  - attr_list
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
  - minify:
      minify_html: true
  - awesome-pages
  - glightbox
